/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/FirstWatch6.glb");

  useFrame(({clock}) => {
    const a = clock.getElapsedTime();
    group.current.rotation.x = Math.PI / 1.75 + Math.cos(a / 4) / 8;
    group.current.rotation.y = Math.sin(a / 4) / 8;
    group.current.rotation.z = (1 + Math.sin(a / 1.5)) / 20;
    group.current.position.y = (1 + Math.sin(a / 1.5)) / 10;

    group.current.opacity = 0;
  })
  return (
    <group scale={30} ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Case_1.geometry}
        material={nodes.Case_1.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Case_2.geometry}
        material={nodes.Case_2.material}
        scale={0.0506671}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wheel.geometry}
        material={nodes.Wheel.material}
        position={[0.0535999, 0.0016741, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.8180043}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Markings.geometry}
        material={nodes.Markings.material}
        position={[0, 0.0141183, -0.0402819]}
        scale={[0.0006171, 0.0004414, 0.0035175]}
      />
      <group
        position={[0, 0.0038393, 0]}
        rotation={[-Math.PI, 0.5968745, -Math.PI]}
        scale={-0.0013973}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004.geometry}
          material={nodes.Plane004.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004_1.geometry}
          material={nodes.Plane004_1.material}
        />
      </group>
      <group
        rotation={[0, 0.9803264, 0]}
        scale={[0.0012734, 0.0012734, 0.0130179]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane003.geometry}
          material={nodes.Plane003.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane003_1.geometry}
          material={nodes.Plane003_1.material}
        />
      </group>
      <group
        rotation={[0, -0.9689773, 0]}
        scale={[-0.0011502, -0.0011502, -0.0186426]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002.geometry}
          material={nodes.Plane002.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002_1.geometry}
          material={nodes.Plane002_1.material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Dial_1.geometry}
        material={materials.Dial}
        position={[0, 0.0025261, 0]}
        scale={0.0448692}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Dial_Wave.geometry}
        material={materials["Dial Wave"]}
        position={[0, 0.0218267, 0]}
        scale={-0.0329619}
      />
    </group>
  );
}

useGLTF.preload("/FirstWatch6.glb");