/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/FirstWatch7.gltf");

  useFrame(({clock}) => {
    const a = clock.getElapsedTime();
    group.current.rotation.x = Math.PI / 1.75 + Math.cos(a / 4) / 8;
    group.current.rotation.y = Math.sin(a / 4) / 8;
    group.current.rotation.z = (1 + Math.sin(a / 1.5)) / 20;
    group.current.position.y = (1 + Math.sin(a / 1.5)) / 10;

    group.current.opacity = 0;
  })
  return (
    <group scale={30} ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Case_1.geometry}
        material={nodes.Case_1.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Case_2.geometry}
        material={nodes.Case_2.material}
        scale={0.050667}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wheel.geometry}
        material={nodes.Wheel.material}
        position={[0.0536, 0.001674, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.818004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Markings.geometry}
        material={nodes.Markings.material}
        position={[0, 0.014118, -0.040282]}
        scale={[0.000617, 0.000441, 0.003517]}
      />
      <group
        position={[0, 0.003839, 0]}
        rotation={[-Math.PI, 0.596875, -Math.PI]}
        scale={-0.001397}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004.geometry}
          material={nodes.Plane004.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004_1.geometry}
          material={nodes.Plane004_1.material}
        />
      </group>
      <group rotation={[0, 0.980326, 0]} scale={[0.001273, 0.001273, 0.013018]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane003.geometry}
          material={nodes.Plane003.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane003_1.geometry}
          material={nodes.Plane003_1.material}
        />
      </group>
      <group
        rotation={[0, -0.968977, 0]}
        scale={[-0.00115, -0.00115, -0.018643]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002.geometry}
          material={nodes.Plane002.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002_1.geometry}
          material={nodes.Plane002_1.material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Dial_1.geometry}
        material={materials.Dial}
        position={[0, 0.002526, 0]}
        scale={0.044869}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Dial_Wave.geometry}
        material={materials["Dial Wave"]}
        position={[0, 0.021827, 0]}
        scale={-0.032962}
      />
    </group>
  );
}

useGLTF.preload("/FirstWatch7.gltf");